#!/bin/sh
cd ~/Projects || exit
SELECTED_DIR=$(find ~/Projects ~/Projects/drupal_modules ~/dotfiles ~/tools -maxdepth 1 -type d | fzf)
echo "$SELECTED_DIR"
cd "$SELECTED_DIR" || exit
tmux new-session -s "${SELECTED_DIR##*/}" -d
tmux rename-window -t "${SELECTED_DIR##*/}" "${SELECTED_DIR##*/}"
tmux send-keys -t "${SELECTED_DIR##*/}" "vi ." Enter
tmux switch -t "${SELECTED_DIR##*/}"
